server {
	listen 80;
	listen [::]:80;
	root /var/www/bulletin.any.com.vn;
	index index.html index.htm index.php;
	server_name bulletin.any.com.vn;

	location / {
		try_files $uri $uri/ =404;
		autoindex on;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/run/php/php7.2-fpm.sock;
	}
}
